Synchronize rc1 and rc2 module definitions

diff --git a/dot/rc1 b/dot/rc1
--- a/dot/rc1
+++ b/dot/rc1
@@ -36,16 +36,16 @@ source_helper() {
 # Main sourcing function
 source_rc() {
     echo -e "   └─ lvl-1 Starting \033[1m ${FUNCNAME[0]} () \033[0m"
-    # Source rc modules
-    local rc_modules=("rc2" "rc3" "rc4" "rc5")
-    echo -e "      └─lvl-2 Source ${rc_modules[*]}"
-    for module in "${rc_modules[@]}"; do
+    # Source rc mod
+    local rc_mod=("rc2" "rc3" "rc4" "rc5")
+    echo -e "      └─lvl-2 Source ${rc_mod[*]}"
+    for module in "${rc_mod[@]}"; do
         source_helper "$DIR/$module"
     done
-    # Source secondary modules
-    local secondary_modules=("env")
-    log "lvl-2" "Sourcing secondary modules: ${secondary_modules[*]}"
-    for module in "${secondary_modules[@]}"; do
+    # Source secondary mod
+    local secondary_mod=("env")
+    log "lvl-2" "Sourcing secondary mod: ${secondary_mod[*]}"
+    for module in "${secondary_mod[@]}"; do
         module_folder="$DIR/$module"
         if [ -d "$module_folder" ]; then
             log "lvl-3" "Processing folder: $module"
@@ -92,8 +92,8 @@ execution_rc() {
     done
 }
 
-# Execution arrangement for modules
-execution_modules() {
+# Execution arrangement for mod
+execution_mod() {
     log "lvl-1" "Starting \033[1m${FUNCNAME[0]} () \033[0m"
     local module_functions=("main_env")
     for func in "${module_functions[@]}"; do
@@ -111,7 +111,7 @@ main_rc() {
     echo -e "└─ lvl-0 Starting \033[1m${FUNCNAME[0]} () \033[0m"
     local source_success=0
     local execution_rc_success=0
-    local execution_modules_success=0
+    local execution_mod_success=0
 
 
     if source_rc; then
@@ -128,14 +128,14 @@ main_rc() {
         unset EXECUTION_RC_SUCCESS
     fi
 
-    if execution_modules; then
+    if execution_mod; then
         export EXECUTION_MODULES_SUCCESS=1
-        execution_modules_success=1
+        execution_mod_success=1
     else
         unset EXECUTION_MODULES_SUCCESS
     fi
 
-    if [[ $source_success -eq 1 && $execution_rc_success -eq 1 && $execution_modules_success -eq 1 ]]; then
+    if [[ $source_success -eq 1 && $execution_rc_success -eq 1 && $execution_mod_success -eq 1 ]]; then
         export RC_SOURCED=1
     else
         unset RC_SOURCED
@@ -150,7 +150,7 @@ main_rc() {
     fi
 
     if [[ -z "${EXECUTION_MODULES_SUCCESS}" ]]; then
-        log "lvl-2" "Error: Execution modules failed." | tee -a "$ERROR_LOG" >&2
+        log "lvl-2" "Error: Execution mod failed." | tee -a "$ERROR_LOG" >&2
     fi
 
     if [[ -z "${RC_SOURCED}" ]]; then
