Update rc, rc2, rc3

diff --git a/dot/rc2 b/dot/rc2
--- a/dot/rc2
+++ b/dot/rc2
@@ -2,35 +2,19 @@
 
 # rc2 module
 
-source_static_functions() {
-    # Error handling function
-    handle_error() {
-        local exit_code=$1
-        local error_message=$2
-        echo "Error: $error_message" >&2
-        exit "$exit_code"
-    }
-
-    # Creates a directory if it doesn't exist, with error handling
-    create_directory() {
-        local dir_path=$1
-        if [[ ! -d "$dir_path" ]]; then
-            mkdir -p "$dir_path" || handle_error 1 "Failed to create directory: $dir_path"
-        fi
-    }
-}
-
-execute_static_functions() {
+setup_static_functions() {
+    # Setup SSH keys and create aliases
     setup_ssh() {
         add_ssh_keys
         # SSH aliases
         alias sk.ed='ssh-keygen -t ed25519 -C "woeiru/lab"'
-        alias sc.ed='ssh-copy-id -i ~/.ssh/id_ed25519.pub root@192.168.178.110'
+        alias sc.ed='ssh-copy-id -i ~/.ssh/id_ed25519.pub root@$SSH_TARGET_IP'
     }
 
+    # Add SSH keys to the agent
     add_ssh_keys() {
         if [ -z "$SSH_AUTH_SOCK" ]; then
-            eval "$(ssh-agent -s)" > /dev/null
+            eval "$(ssh-agent -s)" > /dev/null || echo "Failed to start ssh-agent" >&2
         fi
         local keys=(
             "$HOME/.ssh/id_rsa"
@@ -39,17 +23,19 @@ execute_static_functions() {
         )
         for key in "${keys[@]}"; do
             if [[ -f "$key" && ! $(ssh-add -l | grep -q "$(ssh-keygen -lf "$key" | awk '{print $2}')") ]]; then
-                ssh-add "$key"
+                ssh-add "$key" || echo "Failed to add key: $key" >&2
             fi
         done
     }
 
+    # List all SSH keys in the agent
     list_ssh_keys() {
-        ssh-add -l
+        ssh-add -l || echo "No keys found or ssh-agent is not running" >&2
     }
 
+    # Remove all SSH keys from the agent
     remove_ssh_keys() {
-        ssh-add -D
+        ssh-add -D || echo "Failed to remove SSH keys" >&2
     }
 
     # Call the functions
